name: Send Webhook to Windmill

on:
  push:
    branches:
      - main

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Start Windmill Script
        run: |
          TOKEN='oJROD2DPveQuc9tOHKftXxO9IuCGNcmA'
          BODY='{"test":"hello"}'
          URL='https://app.windmill.dev/api/w/demo/jobs/run/p/u/grahamhaynie/test'
          UUID=$(curl -s -H 'Content-Type: application/json' -H "Authorization: Bearer $TOKEN" -X POST -d "$BODY" $URL)

          echo "Windmill script started with UUID: $UUID"
          echo "UUID=$UUID" >> $GITHUB_ENV

      - name: Wait for Windmill Script Completion
        id: wait-for-completion
        run: |
          UUID=${{ env.UUID }}
          STATUS_URL="https://app.windmill.dev/api/w/demo/jobs_u/completed/get/$UUID"
          while true; do
            RESPONSE=$(curl -s --request GET --url $STATUS_URL --header "Authorization: Bearer $TOKEN")
            echo "Response: $RESPONSE"  # Debug statement to print the response
            SUCCESS=$(echo $RESPONSE | jq -r .success)
            if [ "$SUCCESS" = "true" ]; then
              echo "Windmill script has completed successfully."
              break
            else
              echo "Waiting for Windmill script to complete..."
              sleep 10
            fi
          done
